import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="w-full py-6 mt-12 bg-green-50 border-t border-green-200 text-center text-sm text-green-900">
          <nav className="flex flex-wrap justify-center gap-6">
            <a href="/impressum" className="hover:underline">Impressum</a>
            <a href="/datenschutz" className="hover:underline">Datenschutz</a>
            <a href="/haftungsausschluss" className="hover:underline">Haftungsausschluss</a>
            <a href="/cookies" className="hover:underline">Cookies</a>
          </nav>
        </footer>
      </body>
    </html>
  );
}
